stages:
    - test

linux-test:
    image: rust:trixie
    stage: test
    script:
        - echo "Cloning tools.lua..."
        - cd ..
        - git clone --recursive https://gitlab.com/bp3d/lua.git tools.lua
        - cd -
        - echo "Building..."
        - cargo build
        - echo "Generating distinstall package..."
        - ./target/debug/bp3d package -p distinstall
    artifacts:
        paths:
            - target/install-*

windows-test:
    tags:
        - saas-windows-medium-amd64
    stage: test
    script:
        - echo "Setting up rust/cargo..."
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        - echo "Cloning tools.lua..."
        - cd ..
        - git clone --recursive https://gitlab.com/bp3d/lua.git tools.lua
        - cd -
        - echo "Building..."
        - cargo build
        - echo "Generating distinstall package..."
        - ./target/debug/bp3d package -p distinstall
    artifacts:
        paths:
            - target/install-*

macos-test:
    tags:
        - saas-macos-medium-m1
    stage: test
    script:
        - echo "Setting up rust/cargo..."
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        - echo "Cloning tools.lua..."
        - cd ..
        - git clone --recursive https://gitlab.com/bp3d/lua.git tools.lua
        - cd -
        - echo "Building..."
        - cargo build
        - echo "Generating distinstall package..."
        - ./target/debug/bp3d package -p distinstall
    artifacts:
        paths:
            - target/install-*
