include:
    - project: bp3d/gitlab-tools
      file: workflows/base-jobs.yml

stages:
    - test

linux-test:
    extends:
        - .unix-base-job
    stage: test
    script:
        - subsection setup "Cloning tools.lua..." collapsed
        - cd ..
        - git clone --recursive https://gitlab.com/bp3d/lua.git tools.lua
        - cd -
        - endsection setup
        - subsection build "Building..."
        - cargo build
        - endsection build
        - subsection gen "Generating distinstall package..."
        - ./target/debug/bp3d package -p distinstall
        - endsection gen
    artifacts:
        paths:
            - target/install-*

windows-test:
    extends:
        - .win64-base-job
    stage: test
    script:
        - subsection setup "Cloning tools.lua..." collapsed
        - cd ..
        - git clone --recursive https://gitlab.com/bp3d/lua.git tools.lua
        - cd -
        - endsection setup
        - subsection build "Building..."
        - cargo build
        - endsection build
        - subsection gen "Generating distinstall package..."
        - ./target/debug/bp3d package -p distinstall
        - endsection gen
    artifacts:
        paths:
            - target/install-*

macos-test:
    extends:
        - .mac-base-job
    stage: test
    script:
        - subsection setup "Cloning tools.lua..." collapsed
        - cd ..
        - git clone --recursive https://gitlab.com/bp3d/lua.git tools.lua
        - cd -
        - endsection setup
        - subsection build "Building..."
        - cargo build
        - endsection build
        - subsection gen "Generating distinstall package..."
        - ./target/debug/bp3d package -p distinstall
        - endsection gen
    artifacts:
        paths:
            - target/install-*
